# Generated by Django 5.2.13 on 2026-05-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridewheels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cars', 'Cars'), ('trucks', 'Trucks'), ('bikes', 'Bikes'), ('limited', 'Limited Edition')], max_length=20),
        ),
    ]
