# Generated by Django 5.2.13 on 2026-05-05 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridewheels', '0003_user_address_user_email_user_name_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridewheels.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridewheels.user')),
            ],
        ),
    ]
